#!/usr/bin/env python3
"""
build.py - Automated Builder for UCDOS SDK.LIB
Compiles SOURCE/ using DOSBox-X and Borland C++ 3.1
"""

import sys
import os
import shutil
import subprocess
import argparse
import secrets
import tempfile
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TOOLS_DIR.parent
SOURCE_DIR = REPO_ROOT / "SOURCE"

DOSBOX_BIN: Path = None
BC31_DIR: Path = None


def resolve_paths(cli_dosbox: str = None, cli_bc31: str = None) -> None:
    global DOSBOX_BIN, BC31_DIR

    # DOSBox-X executable
    if cli_dosbox:
        DOSBOX_BIN = Path(cli_dosbox).resolve()
    elif os.environ.get("DOSBOX_BIN"):
        DOSBOX_BIN = Path(os.environ["DOSBOX_BIN"]).resolve()
    elif os.environ.get("DOSBOX"):
        DOSBOX_BIN = Path(os.environ["DOSBOX"]).resolve()
    else:
        which_dosbox = shutil.which("dosbox-x") or shutil.which("dosbox")
        if which_dosbox:
            DOSBOX_BIN = Path(which_dosbox).resolve()

    if not DOSBOX_BIN or not DOSBOX_BIN.is_file():
        print("Error: DOSBox-X binary not found.")
        print("Please provide --dosbox <path-to-dosbox-x> or set the DOSBOX_BIN environment variable.")
        sys.exit(1)

    # Borland C++ 3.1 directory
    if cli_bc31:
        BC31_DIR = Path(cli_bc31).resolve()
    elif os.environ.get("BC31_DIR"):
        BC31_DIR = Path(os.environ["BC31_DIR"]).resolve()
    elif os.environ.get("BORLANDC_DIR"):
        BC31_DIR = Path(os.environ["BORLANDC_DIR"]).resolve()

    if not BC31_DIR or not BC31_DIR.is_dir():
        print("Error: Borland C++ 3.1 directory not specified or does not exist.")
        print("Please provide --bc31 <path-to-bc31> or set the BC31_DIR environment variable.")
        sys.exit(1)


def run_dos(batch_commands: list[str]) -> tuple[int, str]:
    tag = "B" + secrets.token_hex(3).upper()
    bat_file = REPO_ROOT / f"{tag}.BAT"
    log_name = f"{tag}.LOG"
    log_file = SOURCE_DIR / log_name
    STATUS_FILE = SOURCE_DIR / f"{tag}.OK"

    script = [
        "@echo off",
        f'mount t "{BC31_DIR}" > nul',
        r"set PATH=t:\bin;%PATH%",
        "c:",
        r"cd \SOURCE",
    ]
    for INDEX, c in enumerate(batch_commands):
        script.append(f"{c} >> {log_name}")
        script.append("if errorlevel 1 goto FAILED")
        script.append(f"echo STEP_{INDEX} >> {STATUS_FILE.name}")
    script.extend([":FAILED", "exit\r\n"])

    with open(bat_file, "w", encoding="ascii", errors="replace") as f:
        f.write("\r\n".join(script))

    env = os.environ.copy()
    env["SDL_VIDEODRIVER"] = "dummy"

    LOG_PATHS = [log_file, SOURCE_DIR / log_name.lower(), REPO_ROOT / log_name]
    STATUS_PATHS = [STATUS_FILE, STATUS_FILE.with_name(STATUS_FILE.name.lower())]
    try:
        for FILE in LOG_PATHS + STATUS_PATHS:
            FILE.unlink(missing_ok=True)
        res = subprocess.run(
            [str(DOSBOX_BIN), "-fastlaunch", "-nogui", "-silent", "-exit", str(bat_file)],
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        log_output = next((FILE.read_text(encoding="latin1") for FILE in LOG_PATHS if FILE.exists()), "")
        STATUS = next((FILE.read_text(encoding="ascii").split() for FILE in STATUS_PATHS if FILE.exists()), [])
        COMPLETE = bool(batch_commands) and STATUS == [f"STEP_{INDEX}" for INDEX in range(len(batch_commands))]
        return res.returncode if res.returncode else (0 if COMPLETE else 1), log_output
    finally:
        for FILE in LOG_PATHS + STATUS_PATHS + [bat_file]:
            FILE.unlink(missing_ok=True)


def BUILD_OBJECT(COMMAND: str, OBJECT: Path) -> bool:
    # Preserve the previous object, but never let it satisfy this build.
    with tempfile.TemporaryDirectory(prefix="SDK-OBJ-") as BACKUP_DIR:
        BACKUP = Path(BACKUP_DIR) / OBJECT.name
        if OBJECT.exists():
            shutil.copy2(OBJECT, BACKUP)
            OBJECT.unlink()
        COMPLETE = False
        try:
            STATUS, LOG = run_dos([COMMAND])
            if LOG.strip():
                print(LOG.strip())
            COMPLETE = STATUS == 0 and OBJECT.is_file() and OBJECT.stat().st_size > 0
            if not COMPLETE:
                print(f"Build failed: {OBJECT.name} was not freshly generated by a successful command.")
                return False
            print(f"Built {OBJECT.name} ({OBJECT.stat().st_size} bytes)")
            return True
        finally:
            if not COMPLETE:
                OBJECT.unlink(missing_ok=True)
                if BACKUP.exists():
                    shutil.copy2(BACKUP, OBJECT)


def build_c(c_file: str, opt_flags: str = "-O1") -> bool:
    path = Path(c_file)
    name = path.stem.upper()
    print(f"Compiling {path.name} ({opt_flags}) ...")
    cmd = rf"t:\bin\bcc.exe -c -ml {opt_flags} -It:\include -Ic:\include -I. -I.. {path.name}"
    obj_file = SOURCE_DIR / f"{name}.OBJ"
    return BUILD_OBJECT(cmd, obj_file)


def build_asm(asm_file: str) -> bool:
    path = Path(asm_file)
    name = path.stem.upper()
    print(f"Assembling {path.name} ...")
    cmd = rf"t:\bin\tasm.exe /ml /m2 {path.name}"
    obj_file = SOURCE_DIR / f"{name}.OBJ"
    return BUILD_OBJECT(cmd, obj_file)


def build_lib() -> bool:
    print("Packaging SDK.LIB with Borland TLIB 3.02 ...")
    rsp_lines = [
        "+AGI_BMP &",
        "+AGIDRV &",
        "+AGI_WIN &",
        "+DIALOG &",
        "+FILEOPEN &",
        "+GDI &",
        "+HARDERR &",
        "+HELP &",
        "+ICOAPP &",
        "+ICOASKM &",
        "+ICOERROR &",
        "+ICOEXCL &",
        "+ICOEXIT &",
        "+ICON &",
        "+ICOSTOP &",
        "+STA &",
        "+STRELINE &",
        "+TEXTOUT &",
        "+VGAFADE &",
        "+WINSIZE",
    ]
    rsp_file = SOURCE_DIR / "SDK.RSP"
    with open(rsp_file, "w", encoding="ascii") as f:
        f.write("\r\n".join(rsp_lines) + "\r\n")

    root_lib = REPO_ROOT / "SDK.LIB"
    CANDIDATE = REPO_ROOT / ("L" + secrets.token_hex(3).upper() + ".LIB")
    try:
        cmd = rf"t:\bin\tlib.exe /C ..\{CANDIDATE.name} @SDK.RSP"
        ret, log = run_dos([cmd])
        if log.strip():
            print(log.strip())
        if ret != 0 or not CANDIDATE.is_file() or CANDIDATE.stat().st_size < 10:
            print("Library packaging failed; existing SDK.LIB files retained.")
            return False
        with CANDIDATE.open("rb") as FILE:
            HEADER = FILE.read(3)
        if HEADER[0] != 0xF0 or not 7 <= int.from_bytes(HEADER[1:], "little") < CANDIDATE.stat().st_size:
            print("Library packaging failed: invalid OMF library header; existing SDK.LIB files retained.")
            return False
        with tempfile.TemporaryDirectory(prefix="SDK-LIB-") as BACKUP_DIR:
            BACKUP = Path(BACKUP_DIR) / "SDK.LIB"
            if root_lib.exists():
                shutil.copy2(root_lib, BACKUP)
            try:
                CANDIDATE.replace(root_lib)
            except OSError:
                if BACKUP.exists():
                    shutil.copy2(BACKUP, root_lib)
                raise
        print(f"Generated {root_lib.name} ({root_lib.stat().st_size} bytes)")
        return True
    finally:
        CANDIDATE.unlink(missing_ok=True)


MODULES = [
    ("AGI_BMP.C", "-1 -r-"),
    ("AGIDRV.C", "-1 -r-"),
    ("AGI_WIN.C", "-1 -k- -O -Z"),
    ("DIALOG.C", "-ml"),
    ("FILEOPEN.C", "-B -1 -ml"),
    ("HARDERR.C", "-ml -1 -r-"),
    ("HELP.C", "-1 -r-"),
    ("ICON.C", "-ml"),
    ("WINSIZE.C", "-O1 -1"),
    ("GDI.ASM", None),
    ("ICOAPP.ASM", None),
    ("ICOASKM.ASM", None),
    ("ICOERROR.ASM", None),
    ("ICOEXCL.ASM", None),
    ("ICOEXIT.ASM", None),
    ("ICOSTOP.ASM", None),
    ("STA.ASM", None),
    ("STRELINE.ASM", None),
    ("TEXTOUT.ASM", None),
    ("VGAFADE.ASM", None),
]


def build_all() -> bool:
    print("Rebuilding all 20 modules of UCDOS SDK.LIB in SOURCE/ ...")
    success = True
    for item, flags in MODULES:
        if item.endswith(".C"):
            if not build_c(item, flags):
                success = False
        elif item.endswith(".ASM"):
            if not build_asm(item):
                success = False
    if success:
        return build_lib()
    return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build UCDOS SDK.LIB using DOSBox-X and Borland C++ 3.1")
    parser.add_argument("target", nargs="?", default=None, help="Source file to build (e.g. AGI_BMP.C, GDI.ASM)")
    parser.add_argument("opt_flags", nargs="?", default=None, help="Optional compiler flags for single C file")
    parser.add_argument("--all", action="store_true", help="Rebuild all 20 modules and package SDK.LIB")
    parser.add_argument("--lib", action="store_true", help="Package existing OBJ modules into SDK.LIB")
    parser.add_argument("--dosbox", type=str, default=None, help="Path to dosbox-x binary (or set DOSBOX_BIN)")
    parser.add_argument("--bc31", type=str, default=None, help="Path to Borland C++ 3.1 directory (or set BC31_DIR)")

    args = parser.parse_args()

    if not args.all and not args.lib and not args.target:
        parser.print_help()
        sys.exit(1)

    resolve_paths(cli_dosbox=args.dosbox, cli_bc31=args.bc31)

    if args.all:
        ok = build_all()
    elif args.lib:
        ok = build_lib()
    elif args.target:
        if args.target.endswith(".c") or args.target.endswith(".C"):
            flags = args.opt_flags if args.opt_flags else "-O1"
            ok = build_c(args.target, flags)
        elif args.target.endswith(".asm") or args.target.endswith(".ASM"):
            ok = build_asm(args.target)
        else:
            print(f"Unknown extension: {args.target}")
            sys.exit(1)
    else:
        parser.print_help()
        sys.exit(1)

    sys.exit(0 if ok else 1)
